### ISSUE TITLE
Installing on Phoenix 1.3?

### ISSUE THREAD

**Issue by lastobelus** [ChrisYammine/ex_trello#17]
In Phoenix 1.3, application in `mix.exs` looks like this:

```elixir
def application do
    [
      mod: {MyApp.Application, []},
      extra_applications: [:logger, :runtime_tools, :ssl]
    ]
 end
```

Would this be the correct way to add `ex_trello`?

```elixir
def application do
    [
      mod: {MyApp.Application, []},
      extra_applications: [:ex_trello, :logger, :runtime_tools, :ssl]
    ]
 end
```

**Comment by yammine** [comment]
Hey @lastobelus  No need to add it to the extra applications list IIRC (mix should infer it from the deps list)  -- please report back if you have issues 😄

**Comment by lastobelus** [comment]
👍
